version: '3.8'
services:
  db:
    image: postgres:10.12
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

